apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: ruby-app  # Match the labels in your Deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 4567  # Port exposed within the cluster
      targetPort: 4567  # Port your container is listening on
      nodePort: 30015
  externalIPs:
   - 192.168.49.2    