apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-app
  template:
    metadata:
      labels:
        app: ruby-app
    spec:
      containers:
        - name: ruby-container
          image: ma7moudsabra/backend:31
          ports:
            - containerPort: 4567
          resources:
            requests:
              cpu: "200m"   
              memory: "300Mi" 
            limits:
              cpu: "500m"   
              memory: "500Mi"  
