version: '3.8'
services:
    front:
      ports:
        - 3000:3000
      build:
        context: ./frontend/
        dockerfile: Dockerfile
      
    back:
      ports:
      - 4567:4567
      build:
        context: ./ruby/   
        dockerfile: Dockerfile
      depends_on:
        - front
