apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: front-container
          image: ma7moudsabra/frontend:35
          ports: 
           - containerPort: 3000
          resources:
            requests:
              cpu: "200m"   
              memory: "300Mi" 
            limits:
              cpu: "500m"   
              memory: "500Mi"  
          volumeMounts:
            - name: nginx-logs-pvc
              mountPath: /var/log/nginx
     
          env:
            - name: my-configmap
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: REACT_APP_BACKEND_URL
      volumes:
        - name: nginx-logs-pvc
          persistentVolumeClaim:
            claimName: nginx-logs-pvc