apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: front-container
          image: ma7moudsabra/frontend:35
          ports: 
           - containerPort: 3000
          resources:
            requests:
              cpu: "200m"   
              memory: "300Mi" 
            limits:
              cpu: "500m"   
              memory: "500Mi"  
