apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Adjust the access mode as needed (e.g., ReadOnlyMany, ReadWriteMany)
  resources:
    requests:
      storage: 1Gi  # Adjust the storage capacity as needed
